// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitAI - Treino e Dieta Personalizados por IA",
  description: "Plano de treino e dieta 100% personalizado em minutos — criado por IA com base no seu corpo, objetivo, rotina e preferências.",
  keywords: ["treino personalizado", "dieta personalizada", "IA fitness", "personal trainer", "nutrição", "emagrecimento", "ganho de massa"],
  authors: [{ name: "FitAI" }],
  openGraph: {
    title: "FitAI - Treino e Dieta Personalizados por IA",
    description: "Seu plano de treino e dieta prontos, personalizados e fáceis.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
